validator.1.id=VALIDATOR_UNIVERSITY_A
validator.1.institution=University A
validator.1.name=University A Validator
validator.1.publickey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlcSME80aQhw42dF8a+V8iVFG8HyMZiSGjJRhaEcOBfzG05vDKUGei5VfaQpPcW8sMumT265qncsl5Z9KhYX2gSAi21RMUPijcoyg5rD7+6PYw2/ctDqV4kLnI+bIhU2EvLWdipBskT6XZktA4i3Du3dwNgf1EdxRuyHnJgnPNpU4fjZZodKpvRMHZw6QUPEPMKSanjnTzTnnJVmS9woUhEz1fcB7i0Mm5gAQIsu2yQwyKmXlDbXV8iUfLtLD3Y64C0tIG7NuDdqmKM3uBCXprvUJSCBVIEze7jqeoSvc1ndDrbhjVHVga6cGBHFHdui/oWDLL7i2z1e8aacQasPFnQIDAQAB
validator.2.id=VALIDATOR_UNIVERSITY_B
validator.2.institution=University B
validator.2.name=University B Validator
validator.2.publickey=<PUBLIC_KEY_B_PLACEHOLDER>
